#!/bin/bash

[ -d build ] || mkdir -p build

if [ "$1" = "s" ]; then
    echo "Compiling..." && \
    javac -cp src:$CLASSPATH -d build src/ca4006/FileServer.java && \
    echo "Running..." && \
    java -cp build:$CLASSPATH \
        -Djava.rmi.server.codebase=file:build/ \
        -Djava.rmi.server.hostname=$2 \
        ca4006.FileServer "$2" "$3"

else
    echo "Compiling..." && \
    javac -cp src:$CLASSPATH -d build src/ca4006/Client.java && \
    echo "Running..." && \
    java -cp build:$CLASSPATH ca4006.Client "$2" "$3"
fi

